pipeline {
    agent any
    tools {
        maven 'Maven'
        jdk 'C:\\Program Files\\Java\\jdk-17'
    }
    stages {
        stage('Start QA deployment') {
            steps {
                echo 'Start QA deployment'
            }
        }
        stage('Clonar código') {
            steps {
                echo 'Git repository found, preparing to switch branches'
            }
        }
        stage('Compilar') {
            steps {
                echo 'mvn clean compile'
            }
        }
        stage('Pruebas') {
            steps {
                echo 'mvn test'
            }
        }
        stage('Empaquetar') {
            steps {
                echo 'mvn package'
            }
        }
    }
 
    post {
        always {
            echo 'Pipeline finalizado'
        }
        success {
            echo 'Pipeline completado exitosamente'
        }
        failure {
            echo 'El pipeline falló en alguna etapa'
        }
    }
}